name: Build Cordova Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bibanApp  # Already inside bibanApp

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools/latest
          yes | $HOME/Android/Sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Add Android SDK to PATH
        run: echo "PATH=$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Build Debug APK
        run: |
          cordova platform add android@14.0.1 --force
          cordova build android --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: BibanApp-Debug-APK
          path: platforms/android/app/build/outputs/apk/debug/*.apk
